package Proyecto;

import javax.swing.JInternalFrame;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author UserOne
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jdskMenuPrincipal = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmnRegistro = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmnGestionUsu = new javax.swing.JMenuItem();
        jmnGestionHor = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jmnReporte = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jdskMenuPrincipal.setBackground(new java.awt.Color(102, 0, 0));

        javax.swing.GroupLayout jdskMenuPrincipalLayout = new javax.swing.GroupLayout(jdskMenuPrincipal);
        jdskMenuPrincipal.setLayout(jdskMenuPrincipalLayout);
        jdskMenuPrincipalLayout.setHorizontalGroup(
            jdskMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1035, Short.MAX_VALUE)
        );
        jdskMenuPrincipalLayout.setVerticalGroup(
            jdskMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 779, Short.MAX_VALUE)
        );

        jMenuBar1.setBackground(new java.awt.Color(34, 30, 30));

        jMenu1.setBackground(new java.awt.Color(102, 102, 102));
        jMenu1.setText("Control de Asistencia");

        jmnRegistro.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jmnRegistro.setText("Registro de Asistencia");
        jmnRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnRegistroActionPerformed(evt);
            }
        });
        jMenu1.add(jmnRegistro);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Gestión");

        jmnGestionUsu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        jmnGestionUsu.setText("Gestión de Usuarios");
        jmnGestionUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnGestionUsuActionPerformed(evt);
            }
        });
        jMenu2.add(jmnGestionUsu);

        jmnGestionHor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        jmnGestionHor.setText("Gestion de Horario");
        jmnGestionHor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnGestionHorActionPerformed(evt);
            }
        });
        jMenu2.add(jmnGestionHor);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Otros");
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });

        jmnReporte.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        jmnReporte.setText("Reportes");
        jmnReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnReporteActionPerformed(evt);
            }
        });
        jMenu3.add(jmnReporte);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        jMenuItem5.setText("Salir");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jdskMenuPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jdskMenuPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmnRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnRegistroActionPerformed
        // TODO add your handling code here:
        RegistroAsistencia registrar = new RegistroAsistencia(Login.usuario);
        jdskMenuPrincipal.add(registrar);
        registrar.setVisible(true);
        controlVentana(registrar);
    }//GEN-LAST:event_jmnRegistroActionPerformed

    private void jmnGestionUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnGestionUsuActionPerformed
        // TODO add your handling code here:
        GestionUsuario gestionar = new GestionUsuario();
        jdskMenuPrincipal.add(gestionar);
        gestionar.setVisible(true);
        controlVentana(gestionar);
    }//GEN-LAST:event_jmnGestionUsuActionPerformed

    private void jmnGestionHorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnGestionHorActionPerformed
        // TODO add your handling code here:
        Horario horar = new Horario();
        jdskMenuPrincipal.add(horar);
        horar.setVisible(true);
        controlVentana(horar);
    }//GEN-LAST:event_jmnGestionHorActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jMenu3ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        Login ver = new Login();
        ver.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jmnReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnReporteActionPerformed
        // TODO add your handling code here:
        ReporteAsistencias reportar = new ReporteAsistencias();
        jdskMenuPrincipal.add(reportar);
        reportar.setVisible(true);
        controlVentana(reportar);
    }//GEN-LAST:event_jmnReporteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    private void controlVentana(JInternalFrame visioon) {
        jdskMenuPrincipal.removeAll();
        jdskMenuPrincipal.updateUI();
        jdskMenuPrincipal.add(visioon);
        visioon.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    public static javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jdskMenuPrincipal;
    public static javax.swing.JMenuItem jmnGestionHor;
    public static javax.swing.JMenuItem jmnGestionUsu;
    public static javax.swing.JMenuItem jmnRegistro;
    public static javax.swing.JMenuItem jmnReporte;
    // End of variables declaration//GEN-END:variables
}
